package modelo;

// Generated 23/07/2015 09:40:04 AM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.Date;
import java.util.List;

/**
 * Envios generated by hbm2java
 */
public class Envios extends ManejarEntidades implements java.io.Serializable {

	private int idEnvios;
	private Usuarios usuarios;
	private TipoEnvio tipoEnvio;
	private Estatus estatus;
	private Destino destino;
	private Date fechaRegistro;
	private Date fechaModificacion;
	private String tracking;
	private String descripcion;
	private Double peso;
	private Double valor;
	private Boolean listo;
	private String empresa;


	public Envios() {
	}

	public Envios(int idEnvios) {
		this.idEnvios = idEnvios;
	}

	public Envios(int idEnvios, Usuarios usuarios, TipoEnvio tipoEnvio,
			Estatus estatus, Destino destino, Date fechaRegistro,
			Date fechaModificacion, String tracking, String descripcion,
			Double peso, Double valor, Boolean listo, String empresa) {
		this.idEnvios = idEnvios;
		this.usuarios = usuarios;
		this.tipoEnvio = tipoEnvio;
		this.estatus = estatus;
		this.destino = destino;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.tracking = tracking;
		this.descripcion = descripcion;
		this.peso = peso;
		this.valor = valor;
		this.listo = listo;
		this.empresa = empresa;
	}

	public int getIdEnvios() {
		return this.idEnvios;
	}

	public void setIdEnvios(int idEnvios) {
		this.idEnvios = idEnvios;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	public Destino getDestino() {
		return this.destino;
	}

	public void setDestino(Destino destino) {
		this.destino = destino;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getTracking() {
		return this.tracking;
	}

	public void setTracking(String tracking) {
		this.tracking = tracking;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getPeso() {
		return peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public Boolean getListo() {
		return listo;
	}

	public void setListo(Boolean listo) {
		this.listo = listo;
	}
	
	public String getEmpresa() {
		return empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}
	
	public TipoEnvio getTipoEnvio() {
		return this.tipoEnvio;
	}

	public void setTipoEnvio(TipoEnvio tipoEnvio) {
		this.tipoEnvio = tipoEnvio;
	}
	
	
	
	public List<Object[]> ConsultarEnvioxUsuario(String id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.usuarios.idUsuario = "+id+" ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEnvioxUsuario: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarEnvios() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.listo = true ";
				   Sql = Sql + "and a.estatus.siglas <> 'ENT' ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEnvios: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarEnviosEntregados() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.listo = true ";
				   Sql = Sql + "and a.estatus.siglas = 'ENT' ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEnvios: "+ex.getMessage());			
		}
		return objeto;
	}
	
	
	public List<Object[]> ConsultarEnviosxEmpleado(Integer id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.listo = true ";
				   Sql = Sql + "and a.destino.idDestino = "+id+" ";
				   Sql = Sql + "and a.estatus.siglas <> 'ENT' ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEnvios: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarEnviosEntregadosxEmpleado(Integer id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.listo = true ";
				   Sql = Sql + "and a.destino.idDestino = "+id+" ";
				   Sql = Sql + "and a.estatus.siglas = 'ENT' ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEnvios: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarEnviosxId(String id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEnvios, a.usuarios.idUsuario, a.estatus.idEstatus, a.destino.idDestino, a.fechaRegistro, a.fechaModificacion, a.tracking, a.descripcion, a.peso, a.valor, a.listo, a.empresa, a.estatus.siglas, a.tipoEnvio.idTipoEnvio ";
				   Sql = Sql + "from Envios a ";
				   Sql = Sql + "where a.idEnvios = "+id+" ";
				   Sql = Sql + "order by 6 desc";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarUsuariosxId: "+ex.getMessage());			
		}
		return objeto;
	}





	

}
