package modelo;

// Generated 29/07/2015 01:35:38 PM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Estatus generated by hbm2java
 */
public class Estatus extends ManejarEntidades implements java.io.Serializable {

	private int idEstatus;
	private Destino destino;
	private String descripcion;
	private String siglas;
	private Boolean estatus;
	private Set envioses = new HashSet(0);

	public Estatus() {
	}

	public Estatus(int idEstatus) {
		this.idEstatus = idEstatus;
	}

	public Estatus(int idEstatus, Destino destino, String descripcion,
			String siglas, Boolean estatus, Set envioses) {
		this.idEstatus = idEstatus;
		this.destino = destino;
		this.descripcion = descripcion;
		this.siglas = siglas;
		this.estatus = estatus;
		this.envioses = envioses;
	}

	public int getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(int idEstatus) {
		this.idEstatus = idEstatus;
	}

	public Destino getDestino() {
		return this.destino;
	}

	public void setDestino(Destino destino) {
		this.destino = destino;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

	public Set getEnvioses() {
		return this.envioses;
	}

	public void setEnvioses(Set envioses) {
		this.envioses = envioses;
	}
	
	public List<Object[]> ConsultarEstatus(String id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEstatus,a.descripcion,a.siglas ";
				   Sql = Sql + "from Estatus a ";
				   Sql = Sql + "where a.idEstatus = "+id+" order by 1";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEstatus: "+ex.getMessage());			
		}
		return objeto;
	}
	public List<Object[]> ConsultarTodoEstatusDestino(Integer id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEstatus,a.descripcion,a.siglas ";
				   Sql = Sql + "from Estatus a ";
				   Sql = Sql + "where a.destino.idDestino = "+id+" order by 1";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarTodoEstatusDestino: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarTodoEstatus() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idEstatus,a.descripcion,a.siglas ";
				   Sql = Sql + "from Estatus a order by 1 ";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarTodoEstatus: "+ex.getMessage());			
		}
		return objeto;
	}

}
