package modelo;

// Generated 17/07/2015 11:41:36 AM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais extends ManejarEntidades implements java.io.Serializable {

	private int idPais;
	private String nombre;
	private String siglas;
	private Boolean estatus;
	private Set usuarioses = new HashSet(0);

	public Pais() {
	}

	public Pais(int idPais) {
		this.idPais = idPais;
	}

	public Pais(int idPais, String nombre, String siglas, Boolean estatus,
			Set usuarioses) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.siglas = siglas;
		this.estatus = estatus;
		this.usuarioses = usuarioses;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}
	
	public List<Object[]> ConsultarPaisActivo() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idPais, a.nombre, a.siglas ";
				   Sql = Sql + "from Pais a ";
				   Sql = Sql + "where a.estatus = true";
				   
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarPaisActivo: "+ex.getMessage());			
		}
		return objeto;
	}

}
