package modelo;

// Generated 02/11/2015 10:38:51 PM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TipoEnvio generated by hbm2java
 */
public class TipoEnvio extends ManejarEntidades implements java.io.Serializable {

	private int idTipoEnvio;
	private String descripcion;
	private String siglas;
	private Boolean estatus;
	private Set envioses = new HashSet(0);

	public TipoEnvio() {
	}

	public TipoEnvio(int idTipoEnvio) {
		this.idTipoEnvio = idTipoEnvio;
	}

	public TipoEnvio(int idTipoEnvio, String descripcion, String siglas,
			Boolean estatus, Set envioses) {
		this.idTipoEnvio = idTipoEnvio;
		this.descripcion = descripcion;
		this.siglas = siglas;
		this.estatus = estatus;
		this.envioses = envioses;
	}

	public int getIdTipoEnvio() {
		return this.idTipoEnvio;
	}

	public void setIdTipoEnvio(int idTipoEnvio) {
		this.idTipoEnvio = idTipoEnvio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

	public Set getEnvioses() {
		return this.envioses;
	}

	public void setEnvioses(Set envioses) {
		this.envioses = envioses;
	}
	
	public List<Object[]> ConsultarTipoEnvioActivo() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idTipoEnvio, a.descripcion, a.siglas ";
				   Sql = Sql + "from TipoEnvio a ";
				   Sql = Sql + "where a.estatus = true";
				   
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarTipoEnvioActivo: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarTipoEnvioDesc(Integer id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idTipoEnvio, a.descripcion, a.siglas ";
				   Sql = Sql + "from TipoEnvio a ";
				   Sql = Sql + "where a.idTipoEnvio = "+id+" and a.estatus = true";
				   
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarTipoEnvioActivo: "+ex.getMessage());			
		}
		return objeto;
	}

}
