package modelo;

// Generated 16/07/2015 12:58:58 PM by Hibernate Tools 3.4.0.CR1

import general.ManejarEntidades;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario extends ManejarEntidades implements java.io.Serializable {

	private int idTipoUsuario;
	private String nombre;
	private String siglas;
	private boolean estatus;
	private Set usuarioses = new HashSet(0);

	public TipoUsuario() {
	}

	public TipoUsuario(int idTipoUsuario, String nombre, String siglas,
			boolean estatus) {
		this.idTipoUsuario = idTipoUsuario;
		this.nombre = nombre;
		this.siglas = siglas;
		this.estatus = estatus;
	}

	public TipoUsuario(int idTipoUsuario, String nombre, String siglas,
			boolean estatus, Set usuarioses) {
		this.idTipoUsuario = idTipoUsuario;
		this.nombre = nombre;
		this.siglas = siglas;
		this.estatus = estatus;
		this.usuarioses = usuarioses;
	}

	public int getIdTipoUsuario() {
		return this.idTipoUsuario;
	}

	public void setIdTipoUsuario(int idTipoUsuario) {
		this.idTipoUsuario = idTipoUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}
	
	public List<Object[]> ConsultarTipoUsuarioActivo() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idTipoUsuario, a.nombre, a.siglas ";
				   Sql = Sql + "from TipoUsuario a ";
				   Sql = Sql + "where a.estatus = true";
				   
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarTipoUsuarioActivo: "+ex.getMessage());			
		}
		return objeto;
	}

}
