package modelo;

import general.ManejarEntidades;

import java.util.Date;
import java.util.List;

// Generated 17/07/2015 11:41:36 AM by Hibernate Tools 3.4.0.CR1

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios extends ManejarEntidades implements java.io.Serializable {

	private int idUsuario;
	private TipoUsuario tipoUsuario;
	private Pais pais;
	private Destino destino;
	private String usuario;
	private String nombre;
	private String apellido;
	private String clave;
	private String identificador;
	private boolean estatus;
	private boolean activo;
	private String direccion;
	private String telefono;
	private String correo;
	private String fechaRegistro;

	public Usuarios() {
	}

	public Usuarios(int idUsuario, TipoUsuario tipoUsuario, Pais pais,
			Destino destino, String usuario, String nombre, String apellido,
			String clave, boolean estatus,
			boolean activo, String direccion, String telefono, String correo) {
		this.idUsuario = idUsuario;
		this.tipoUsuario = tipoUsuario;
		this.pais = pais;
		this.destino = destino;
		this.usuario = usuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.clave = clave;
		this.estatus = estatus;
		this.activo = activo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
	}

	public Usuarios(int idUsuario, TipoUsuario tipoUsuario, Pais pais,
			Destino destino, String usuario, String nombre, String apellido,
			String clave, String identificador, boolean estatus,
			boolean activo, String direccion, String telefono, String correo, String fechaRegistro) {
		this.idUsuario = idUsuario;
		this.tipoUsuario = tipoUsuario;
		this.pais = pais;
		this.destino = destino;
		this.usuario = usuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.clave = clave;
		this.identificador = identificador;
		this.estatus = estatus;
		this.activo = activo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.fechaRegistro = fechaRegistro;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Destino getDestino() {
		return this.destino;
	}

	public void setDestino(Destino destino) {
		this.destino = destino;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	
	

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
	public String getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}
	
	public List<Object[]> ConsultarUsuarioXLoginActivo(String cusuario) {
		List<Object[]> objeto = null;
		try {
				   
			
				   String Sql ="select a.idUsuario, a.nombre, a.apellido, a.identificador, a.tipoUsuario.siglas, a.clave, a.activo, a.destino.siglas, a.correo,a.destino.idDestino ";
				   Sql = Sql + "from Usuarios a ";
				   Sql = Sql + "where a.usuario ='"+cusuario+"' and a.estatus = true";
				   
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarUsuarioXLoginActivoValores: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarEmpleadosActivo() {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idUsuario, a.usuario ,a.nombre, a.apellido, a.identificador, a.tipoUsuario.nombre, a.clave, a.activo, a.destino.siglas, a.correo, a.tipoUsuario.idTipoUsuario ";
				   Sql = Sql + "from Usuarios a ";
				   Sql = Sql + "where a.estatus = true ";
				   Sql = Sql + "and a.tipoUsuario.siglas = 'EM' ";
				   Sql = Sql + "or a.tipoUsuario.siglas = 'AD' ";
				   Sql = Sql + "or a.tipoUsuario.siglas = 'ADP' ";
				   Sql = Sql + "or a.tipoUsuario.siglas = 'ADV' ";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarEmpleadosActivo: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarUsuarios(Boolean activo) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idUsuario, a.usuario ,a.nombre, a.apellido, a.identificador, a.clave, a.activo, a.destino.idDestino, a.correo, a.tipoUsuario.idTipoUsuario, a.pais.idPais ";
				   Sql = Sql + "from Usuarios a ";
				   Sql = Sql + "where a.estatus = true ";
				   Sql = Sql + "and a.activo = '"+activo+"' ";
				   Sql = Sql + "and a.tipoUsuario.siglas = 'US' ";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarUsuarios: "+ex.getMessage());			
		}
		return objeto;
	}
	
	public List<Object[]> ConsultarUsuariosxDestino(Boolean activo, Integer idDestino) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idUsuario, a.usuario ,a.nombre, a.apellido, a.identificador, a.clave, a.activo, a.destino.idDestino, a.correo, a.tipoUsuario.idTipoUsuario, a.pais.idPais ";
				   Sql = Sql + "from Usuarios a ";
				   Sql = Sql + "where a.estatus = true ";
				   Sql = Sql + "and a.activo = '"+activo+"' ";
				   Sql = Sql + "and a.tipoUsuario.siglas = 'US' ";
				   Sql = Sql + "and a.destino.idDestino = "+idDestino+" ";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarUsuariosxDestino: "+ex.getMessage());			
		}
		return objeto;
	}
	
	
	public List<Object[]> ConsultarUsuariosxId(String id) {
		List<Object[]> objeto = null;
		try {
				   String Sql ="select a.idUsuario, a.usuario ,a.nombre,a.apellido, a.clave, a.identificador, a.tipoUsuario.idTipoUsuario, a.estatus, a.activo,  a.pais.idPais, a.direccion, a.telefono, a.destino.idDestino, a.correo, a.fechaRegistro ";
				   Sql = Sql + "from Usuarios a ";
				   Sql = Sql + "where a.idUsuario = "+id+" ";
			objeto = this.ConsultarListaValores(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarUsuariosxId: "+ex.getMessage());			
		}
		return objeto;
	}



}
